pipeline {
    agent any

    environment {
        DOCKER_HOST = "tcp://host.docker.internal:2375"
    }

    stages {

        stage('Test Docker Connection') {
            steps {
                sh '''
                    docker ps
                '''
            }
        }

        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                    GOCACHE = "${WORKSPACE}/.gocache"
                    GOPATH  = "${WORKSPACE}/.gopath"
                }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        echo "Running tests in container..."
                        mkdir -p .gocache .gopath
                        go env
                        go test -v ./... | go-junit-report > test-results.xml
                        cat test-results.xml

                        # Generate coverage report
                        go test -coverprofile=coverage.out -covermode=atomic ./...
                        go tool cover -html=coverage.out -o coverage.html

                        mkdir -p reports
                        mv coverage.html reports/
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-backend/test-results.xml'
                    publishHTML(target: [
                        reportDIr: 'bugtracker-backend/reports',
                        reportFiles: 'coverage.html',
                        reportName: 'Backend Coverage Report'
                    ])
                }
            }
        }
        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }

    }
}
