pipeline {
    agent any

    stages {

        stage('Execute Unit Tests') {
            parallel {

                stage('Test Docker Connection') {
                    steps {
                        sh '''
                            docker ps
                        '''
                    }
                }

                stage('Unit Tests - Backend') {
                    agent {
                        docker {
                            image 'snakee/golang-junit:1.21'
                            reuseNode true
                        }
                    }
                    environment {
                        GOCACHE = "${WORKSPACE}/.gocache"
                        GOPATH  = "${WORKSPACE}/.gopath"
                    }
                    steps {
                        dir('bugtracker-backend') {
                            sh 'mkdir -p test-results .gocache .gopath'
                            sh '''
                                echo "Running tests in container..."
                                go env
                                go test -v ./... | go-junit-report > test-results/test-results.xml
                                cat test-results/test-results.xml

                                # Generate coverage report
                                go test -coverprofile=coverage.out -covermode=atomic ./...
                                go tool cover -html=coverage.out -o coverage.html

                                mkdir -p reports
                                mv coverage.html reports/
                            '''
                        }
                    }
                    post {
                        always {
                            junit 'bugtracker-backend/test-results/test-results.xml'
                            publishHTML(target: [
                                reportDir: 'bugtracker-backend/reports',
                                reportFiles: 'coverage.html',
                                reportName: 'Backend Coverage Report'
                            ])
                        }
                    }
                }

                stage('Unit Tests - Frontend') {
                    agent {
                        docker {
                            image 'node:20-alpine'
                            reuseNode true
                        }
                    }
                    steps {
                        dir('bugtracker-frontend') {
                            sh '''
                                echo "Running frontend tests..."
                                mkdir -p test-results reports/coverage

                                npm ci
                                npm test

                                rm -rf reports/coverage
                                mkdir -p reports/coverage
                                mv coverage reports/
                            '''
                        }
                    }
                    post {
                        always {
                            junit allowEmptyResults: true,
                                  testResults: 'bugtracker-frontend/test-results/test-results.xml'
                            publishHTML target: [
                                reportDir: 'bugtracker-frontend/reports/coverage',
                                reportFiles: 'index.html',
                                reportName: 'Frontend Coverage Report'
                            ]
                        }
                    }
                }

            }
        }

        stage("Launch Applicaton") {
            agent {
                docker {
                    image "docker:27.5.1"
                    reuseNode true
                    args "-v /var/run/docker.sock:/var/run/docker.sock -u 0 --entrypoint=''"
                }
            }
            steps {
                sh '''
                    echo "Stopping old bug-tracker containers..."
                    docker stop workspace-backend-1 || true
                    docker stop workspace-frontend-1 || true
                    docker rm workspace-backend-1 || true
                    docker rm workspace-frontend-1 || true

                    echo "Stopping workspace containers..."
                    docker compose down || true

                    echo "Starting fresh containers..."
                    docker compose up --build -d
                '''
            }
        }

        stage("API Tests") {
            agent {
                docker {
                    image 'mcr.microsoft.com/playwright:v1.50.0-jammy'
                    reuseNode true
                    args '-u 0 --network=host'
                }
            }
            steps {
                dir('tests-api') {
                    sh 'mkdir -p test-results playwright-report'
                    sh 'npx wait-port http://localhost:8080/api/health -t 30000'
                    sh 'npm ci'
                    sh 'npx playwright test'
                }
            }
            post {
                always {
                    junit allowEmptyResults: true,
                          testResults: 'tests-api/test-results/results.xml'
                    publishHTML target: [
                        reportDir: 'tests-api/playwright-report',
                        reportFiles: 'index.html',
                        reportName: 'Playwright API Test Report'
                    ]
                }
            }
        }

        stage('E2E Tests') {
            agent {
                docker {
                    image 'mcr.microsoft.com/playwright:v1.50.0-jammy'
                    reuseNode true
                    args '-u 0 --network=host'
                }
            }
            steps {
                dir('tests-e2e') {
                    sh 'mkdir -p test-results playwright-report'
                    sh 'npm ci'
                    sh 'npx playwright test'
                }
            }
            post {
                always {
                    junit allowEmptyResults: true,
                          testResults: 'tests-e2e/test-results/results.xml'
                    publishHTML target: [
                        reportDir: 'tests-e2e/playwright-report',
                        reportFiles: 'index.html',
                        reportName: 'Playwright E2E Test Report'
                    ]
                }
            }
        }

        stage('Performance Tests') {
            agent {
                docker {
                    image 'grafana/k6:latest'
                    reuseNode true
                    args '--network=host -u root --entrypoint=""'
                }
            }
            steps {
                dir('tests-perf') {
                    sh 'k6 run script.js'
                }
            }
            post {
                always {
                    publishHTML target: [
                        reportDir: 'tests-perf',
                        reportFiles: 'perf-results.html',
                        reportName: 'Performance Test Results Report'
                    ]
                }
            }
        }

        stage('Deploy Staging') {
            when {
                expression {
                    return env.GIT_BRANCH == 'origin/main'
                }
            }
            environment {
                FLY_API_TOKEN = credentials('FLY_API_TOKEN')
                FLYCTL_INSTALL = "${env.WORKSPACE.replaceALL(' ','')}/.fly"
                PATH = "$FLYCTL_INSTALL/bin:$PATH"
                HOME = "${WORKSPACE}"
            }
            stages {

                stage('Install Flyctl') {
                    steps {
                        sh 'mkdir -p $FLYCTL_INSTALL'
                        sh 'curl -L https://fly.io/install.sh | sh'
                        sh 'flyctl version'
                    }
                }

                stage('Deploy Backend') {
                    steps {
                        dir('bugtracker-backend') {
                            sh 'flyctl dedploy -c fly.staging.toml --remote-only'
                        }
                    }
                }

                stage('Deploy Frontend') {
                    steps {
                        dir('bugtracker-frontend') {
                            sh 'flyctl dedploy -c fly.staging.toml --remote-only'
                        }
                    }
                }

            }
        }

    }
}